### ISSUE TITLE
File /var/cache/pacman/pkg/ibus-teni-1.3.2-1-any.pkg.tar.xz is corrupted (invalid or corrupted package (checksum))

### ISSUE THREAD

**Issue by nguyenlekhtn** [teni-ime/ibus-teni#40]
OS: Manjaro (Arch)

After adding repos and run sudo pacman -S home_vietnamese_Arch/ibus-teni, 
> resolving dependencies...
> looking for conflicting packages...
> 
> Packages (6) ibus-1.5.19-1  pygobject2-devel-2.28.7-2  python2-dbus-1.2.8-2
>              python2-gobject-3.28.3-2  python2-gobject2-2.28.7-2
>              ibus-teni-1.3.2-1
> 
> Total Installed Size:  13,13 MiB
> 
> :: Proceed with installation? [Y/n] y
> (6/6) checking keys in keyring                     [###################] 100%
> (6/6) checking package integrity                   [###################] 100%
> :: File /var/cache/pacman/pkg/ibus-teni-1.3.2-1-any.pkg.tar.xz is corrupted (invalid or corrupted package (checksum)).

Try to grab the binary packages directly and run sudo pacman -U ibus-teni-1.3.2-1-any.pkg.tar.xz led to:

> error: '/var/cache/pacman/pkg/ibus-teni-1.3.2-1-any.pkg.tar.xz': package missing required signature

Maybe some problem with signing package???

**Comment by teni-ime** [comment]
Please follow the installation guide for Arch.

Add repository and install manually

For Arch Linux, edit /etc/pacman.conf and add the following (note that the order of repositories in pacman.conf is important, since pacman always downloads the first found package):
[openSUSE_Tools_Arch]
SigLevel = Never
Server = https://download.opensuse.org/repositories/openSUSE:/Tools/Arch/$arch
Then run the following as root
pacman -Syu
pacman -S openSUSE_Tools_Arch/osc
